# Generated by Django 4.0.2 on 2022-02-13 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('telegram_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='phone number should contain 10 digits without country code', regex='^\\d{10}$')])),
            ],
        ),
    ]
